services:
    portfolio:
        container_name: portfolio
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env
        networks:
            - proxy_network
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.portfolio.rule=Host(`${PINOCLOUD_PUBLIC}`)"
            - "traefik.http.routers.portfolio.entrypoints=websecure"
            - "traefik.http.routers.portfolio.tls=true"

            - "traefik.http.services.portfolio.loadbalancer.server.scheme=http"
            - "traefik.http.services.portfolio.loadbalancer.server.port=4321"
networks:
    proxy_network:
        external: true
